"use client";

import { LAYOUT_ARCHETYPES, type BrandSpec } from "@brandrail/spec";
import { useState } from "react";

type SavedRender = { id: string; createdAt: string; manifest: { brand: string; brief: string; assets: Array<{ filename: string; format: string }> } };
type Tab = "system" | "assets" | "history";

export function BrandWorkspace({ initialSpec, owner, genUsed, genLimit, genConfigured, renders }: { initialSpec: BrandSpec; owner: boolean; genUsed: number; genLimit: number; genConfigured: boolean; renders: SavedRender[] }) {
  const [spec, setSpec] = useState(initialSpec);
  const [draft, setDraft] = useState(() => draftFrom(initialSpec));
  const [tab, setTab] = useState<Tab>("system");
  const [subject, setSubject] = useState("");
  const [busy, setBusy] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);

  async function saveSystem() {
    setBusy("save"); setMessage(null);
    const patch = {
      identity: {
        colors: { roles: draft.colors },
        typography: { display: { family: draft.displayFamily }, body: { family: draft.bodyFamily } },
        spacing: { unit: draft.spacingUnit, grid: draft.grid },
        logo: { clearspace: draft.clearspace, minSizePx: draft.logoMinSize },
      },
      composition: { alignment: draft.alignment, whitespaceMinPct: draft.whitespace, densityMaxElementsPerZone: draft.density, layoutArchetypes: draft.archetypes },
      imagery: { photography: { ...spec.imagery.photography, style: draft.photoStyle, allowed: draft.photoAllowed }, illustration: { allowed: draft.illustrationAllowed }, aiFences: { backgrounds: draft.aiBackgrounds, subjects: false } },
      voice: { tone: lines(draft.tone), banned: lines(draft.banned), required: lines(draft.required), ctaStyle: draft.ctaStyle, emojiMax: draft.emojiMax, hashtagMax: draft.hashtagMax },
    };
    const res = await fetch("/api/spec", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ brand: spec.meta.name, patch }) });
    const body = await res.json() as { spec?: BrandSpec; error?: string; issues?: Array<{ path: string; message: string }> };
    if (res.ok && body.spec) { setSpec(body.spec); setDraft(draftFrom(body.spec)); setMessage(`Brand system saved as v${body.spec.meta.version}. Every future asset now inherits it.`); }
    else setMessage(body.issues?.[0] ? `${body.issues[0].path}: ${body.issues[0].message}` : body.error ?? "Could not save changes");
    setBusy(null);
  }

  async function generate() {
    setBusy("generate"); setMessage(null);
    const res = await fetch("/api/background", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ brand: spec.meta.name, subject }) });
    const body = await res.json() as { version?: number; error?: string };
    if (res.ok) { setMessage(`Background generated and pinned to BrandSpec v${body.version}.`); setSubject(""); }
    else setMessage(body.error ?? "Could not generate the background");
    setBusy(null);
  }

  function acceptUploaded(next: BrandSpec, label: string) { setSpec(next); setDraft(draftFrom(next)); setMessage(`${label} added and saved as BrandSpec v${next.meta.version}.`); }

  return <main className="mx-auto max-w-6xl px-5 py-10 sm:px-6">
    <header className="flex flex-wrap items-end justify-between gap-5"><div><a href="/dashboard" className="eyebrow hover:text-bone">← WORKSPACE</a><p className="eyebrow text-signal mt-6">BRAND OPERATING SYSTEM</p><h1 className="font-display text-4xl font-bold mt-2">{spec.meta.displayName ?? spec.meta.name}</h1><p className="font-mono text-xs text-muted mt-2">{spec.meta.name} · BrandSpec v{spec.meta.version} · versioned and portable</p></div><a href={`/api/spec?brand=${encodeURIComponent(spec.meta.name)}`} className="btn-ghost">Export BrandSpec ↓</a></header>
    {message && <div className="panel border-signal/40 px-4 py-3 mt-7 text-sm">{message}</div>}
    <nav className="mt-9 flex overflow-x-auto border-b border-hairline">{(["system", "assets", "history"] as Tab[]).map((item) => <button key={item} onClick={() => setTab(item)} className={`px-5 py-3 font-mono text-[11px] uppercase tracking-wider ${tab === item ? "border-b-2 border-signal text-bone" : "text-muted hover:text-bone"}`}>{item === "system" ? "Brand rules" : item === "assets" ? "Asset library" : `History (${renders.length})`}</button>)}</nav>
    {tab === "system" && <SystemEditor spec={spec} draft={draft} setDraft={setDraft} owner={owner} busy={busy} save={() => void saveSystem()} />}
    {tab === "assets" && <section className="mt-8 grid gap-5 lg:grid-cols-[1fr_1fr]">
      <div className="space-y-5"><AssetInventory spec={spec} /><AssetUploader brand={spec.meta.name} owner={owner} onUploaded={acceptUploaded} /></div>
      <div className="space-y-5"><div className="panel p-6"><p className="eyebrow text-bone">GENERATIVE IMAGE RAIL</p><div className="font-display text-3xl font-bold mt-3">{genUsed} <span className="font-mono text-sm text-muted">/ {genLimit}</span></div><p className="text-muted text-sm mt-3 leading-relaxed">Describe a scene. Brandrail generates imagery only, pins it into the spec, then reuses it deterministically.</p>{owner && genConfigured ? <><textarea className="field mt-5 min-h-24" placeholder="Sunlit studio desk, warm stone textures, no text or logos" value={subject} onChange={(e) => setSubject(e.target.value)} /><button onClick={() => void generate()} disabled={!subject.trim() || busy === "generate"} className="btn w-full mt-3">{busy === "generate" ? "Generating…" : "Generate and pin background"}</button></> : <p className="font-mono text-xs text-muted mt-4">{owner ? "Add FAL_KEY to this instance to enable generation." : "Only the workspace owner can change the BrandSpec."}</p>}</div><GuidelineSummary spec={spec} /></div>
    </section>}
    {tab === "history" && <RenderHistory renders={renders} />}
  </main>;
}

type Draft = ReturnType<typeof draftFrom>;
function SystemEditor({ spec, draft, setDraft, owner, busy, save }: { spec: BrandSpec; draft: Draft; setDraft: (draft: Draft) => void; owner: boolean; busy: string | null; save: () => void }) {
  const update = <K extends keyof Draft>(key: K, value: Draft[K]) => setDraft({ ...draft, [key]: value });
  return <section className="mt-8 space-y-5">
    <div className="grid gap-5 lg:grid-cols-2"><Panel title="Identity" body="The tokens every template consumes."><div className="grid grid-cols-2 gap-3">{Object.entries(draft.colors).filter((entry): entry is [string,string] => typeof entry[1] === "string").map(([role,value]) => <label key={role} className="border border-hairline p-3"><span className="eyebrow block mb-2">{role}</span><span className="flex gap-2"><input type="color" value={value} onChange={(e) => update("colors", { ...draft.colors, [role]: e.target.value })} disabled={!owner} /><input className="field !py-2 font-mono" value={value} onChange={(e) => update("colors", { ...draft.colors, [role]: e.target.value })} disabled={!owner} /></span></label>)}</div><div className="grid sm:grid-cols-2 gap-3 mt-4"><Field label="Display type" value={draft.displayFamily} onChange={(value) => update("displayFamily", value)} disabled={!owner} /><Field label="Body type" value={draft.bodyFamily} onChange={(value) => update("bodyFamily", value)} disabled={!owner} /><NumberField label="Spacing unit" value={draft.spacingUnit} min={2} max={32} onChange={(value) => update("spacingUnit", value)} disabled={!owner} /><SelectField label="Grid" value={draft.grid} values={["12col","8col","4col"]} onChange={(value) => update("grid", value as Draft["grid"])} disabled={!owner} /><Field label="Logo clearspace" value={draft.clearspace} onChange={(value) => update("clearspace", value)} disabled={!owner} /><NumberField label="Logo minimum px" value={draft.logoMinSize} min={8} max={300} onChange={(value) => update("logoMinSize", value)} disabled={!owner} /></div></Panel>
      <Panel title="Voice" body="The copy gate rejects language outside these rails."><Field label="Tone · comma or line separated" value={draft.tone} onChange={(value) => update("tone", value)} disabled={!owner} /><TextArea label="Banned words · one per line" value={draft.banned} onChange={(value) => update("banned", value)} disabled={!owner} /><TextArea label="Required phrases · one per line" value={draft.required} onChange={(value) => update("required", value)} disabled={!owner} /><div className="grid grid-cols-3 gap-3"><SelectField label="CTA style" value={draft.ctaStyle} values={["imperative-short","imperative","conversational","formal"]} onChange={(value) => update("ctaStyle", value as Draft["ctaStyle"])} disabled={!owner} /><NumberField label="Emoji max" value={draft.emojiMax} min={0} max={10} onChange={(value) => update("emojiMax", value)} disabled={!owner} /><NumberField label="Hashtag max" value={draft.hashtagMax} min={0} max={10} onChange={(value) => update("hashtagMax", value)} disabled={!owner} /></div></Panel></div>
    <div className="grid gap-5 lg:grid-cols-2"><Panel title="Composition" body="Hard layout constraints, enforced before an asset can leave the renderer."><div className="grid grid-cols-3 gap-3"><SelectField label="Alignment" value={draft.alignment} values={["left","center","mixed"]} onChange={(value) => update("alignment", value as Draft["alignment"])} disabled={!owner} /><NumberField label="Whitespace %" value={draft.whitespace} min={0} max={80} onChange={(value) => update("whitespace", value)} disabled={!owner} /><NumberField label="Max density" value={draft.density} min={1} max={10} onChange={(value) => update("density", value)} disabled={!owner} /></div><p className="eyebrow text-bone mt-5 mb-2">ALLOWED TEMPLATES</p><div className="grid grid-cols-2 gap-2">{LAYOUT_ARCHETYPES.map((name) => <label key={name} className={`cursor-pointer border px-3 py-2 font-mono text-[10px] ${draft.archetypes.includes(name) ? "border-signal text-bone" : "border-hairline text-muted"}`}><input className="sr-only" type="checkbox" checked={draft.archetypes.includes(name)} onChange={() => update("archetypes", draft.archetypes.includes(name) ? draft.archetypes.filter((item) => item !== name) : [...draft.archetypes, name])} disabled={!owner} />{name}</label>)}</div></Panel>
      <Panel title="Imagery" body="Decide what can enter the system before anyone generates a post."><Field label="Photography style" value={draft.photoStyle} onChange={(value) => update("photoStyle", value)} disabled={!owner} /><div className="mt-4 space-y-2"><Toggle label="Allow brand photography" checked={draft.photoAllowed} onChange={(value) => update("photoAllowed", value)} disabled={!owner} /><Toggle label="Allow illustration" checked={draft.illustrationAllowed} onChange={(value) => update("illustrationAllowed", value)} disabled={!owner} /><Toggle label="Allow fenced AI backgrounds" checked={draft.aiBackgrounds} onChange={(value) => update("aiBackgrounds", value)} disabled={!owner} /></div><p className="font-mono text-[10px] text-muted mt-5">AI subjects remain blocked by the spec. Brandrail can fill background zones; it cannot invent people or products.</p></Panel></div>
    {owner ? <div className="sticky bottom-4 flex justify-end"><button onClick={save} disabled={busy === "save" || draft.archetypes.length === 0} className="btn shadow-[0_0_30px_rgba(255,77,0,.18)]">{busy === "save" ? "Saving system…" : `Save BrandSpec v${spec.meta.version + 1}`}</button></div> : <p className="font-mono text-xs text-muted">Reviewer view · only the workspace owner can change brand rules.</p>}
  </section>;
}

function AssetInventory({ spec }: { spec: BrandSpec }) { const logo = spec.identity.logo.assets.primary; return <div className="panel p-6"><p className="eyebrow text-bone">CURRENT LIBRARY</p><div className="grid grid-cols-2 gap-3 mt-4"><AssetStat value={logo ? 1 : 0} label="primary logo" /><AssetStat value={spec.imagery.photos.length} label="brand photos" /><AssetStat value={spec.identity.typography.display.sources.length} label="display fonts" /><AssetStat value={spec.identity.typography.body.sources.length} label="body fonts" /></div>{logo && <div className="border border-hairline bg-bone p-4 mt-4"><img src={assetUrl(logo)} alt="Primary brand logo" className="h-16 w-full object-contain" /></div>}{spec.imagery.photos.length > 0 && <div className="grid grid-cols-3 gap-2 mt-4">{spec.imagery.photos.map((photo) => <img key={photo} src={assetUrl(photo)} alt="Brand library" className="aspect-square w-full object-cover border border-hairline" />)}</div>}</div>; }
function AssetUploader({ brand, owner, onUploaded }: { brand: string; owner: boolean; onUploaded: (spec: BrandSpec, label: string) => void }) { const [kind,setKind]=useState("logo"); const [file,setFile]=useState<File|null>(null); const [weight,setWeight]=useState(400); const [notes,setNotes]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null); async function upload(){if(!file)return;setBusy(true);setError(null);const data=await fileData(file);const res=await fetch("/api/brand-asset",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({brand,kind,filename:file.name,data,...(kind.startsWith("font-")?{weight}:{}),...(kind==="guidelines"?{notes}:{})})});const body=await res.json() as {spec?:BrandSpec;error?:string};if(res.ok&&body.spec){onUploaded(body.spec,file.name);setFile(null);setNotes("");}else setError(body.error??"Upload failed");setBusy(false);} const accept=kind.startsWith("font-")?".woff2,.woff,.ttf,.otf":kind==="guidelines"?".pdf,.txt,.md":"image/png,image/jpeg,image/webp,image/gif,image/svg+xml"; return <div className="panel p-6"><p className="eyebrow text-bone">ADD BRAND MATERIAL</p><p className="text-muted text-sm mt-2">Upload the real assets. They are pinned into the versioned spec instead of referenced from a fragile URL.</p><select className="field mt-5" value={kind} onChange={(e)=>{setKind(e.target.value);setFile(null);}} disabled={!owner}><option value="logo">Primary logo</option><option value="mark">Logo mark</option><option value="photo">Brand photography</option><option value="font-display">Display font</option><option value="font-body">Body font</option><option value="guidelines">Brand guidelines</option></select>{kind.startsWith("font-")&&<NumberField label="Font weight" value={weight} min={100} max={900} onChange={setWeight} disabled={!owner}/>}<label className="mt-3 block border border-dashed border-hairline p-5 text-center text-sm text-muted hover:border-signal"><input type="file" className="sr-only" accept={accept} onChange={(e)=>setFile(e.target.files?.[0]??null)} disabled={!owner}/>{file?`${file.name} · ${(file.size/1024/1024).toFixed(1)} MB`:`Choose ${kind.replace("-"," ")} file · max 10 MB`}</label>{kind==="guidelines"&&<textarea className="field mt-3 min-h-24" placeholder="Paste the key rules from the document so the copy and judgment rails can enforce them…" value={notes} onChange={(e)=>setNotes(e.target.value)} disabled={!owner}/>} {error&&<p className="font-mono text-xs text-signal mt-2">{error}</p>}<button className="btn w-full mt-3" disabled={!owner||!file||busy} onClick={()=>void upload()}>{busy?"Pinning asset…":"Upload and create new version"}</button></div>; }
function GuidelineSummary({ spec }: { spec: BrandSpec }) { const docs=spec.judgment.positive.filter((item)=>item.note.startsWith("Brand guidelines:")); return <div className="panel p-6"><p className="eyebrow text-bone">GUIDELINES INGESTED ({docs.length})</p>{docs.length?<ul className="mt-3 space-y-2">{docs.map((item,index)=><li key={`${item.note}-${index}`} className="border border-hairline px-3 py-2 text-sm">{item.note.replace("Brand guidelines: ","")}</li>)}</ul>:<p className="text-muted text-sm mt-3">Upload a PDF, text or markdown guide and paste its enforceable rules.</p>}<p className="font-mono text-[10px] text-muted mt-4">{spec.judgment.promptSnippets.length} written judgment rules currently feed the brand gate.</p></div>; }
function RenderHistory({ renders }: { renders: SavedRender[] }) { return <section className="mt-8">{renders.length===0?<p className="text-muted text-sm">No saved assets for this brand yet.</p>:<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{renders.map((render)=>{const cover=render.manifest.assets[0];return <article className="panel overflow-hidden" key={render.id}>{cover&&<img className="aspect-video w-full object-cover border-b border-hairline" src={`/api/asset/${encodeURIComponent(render.id)}/${encodeURIComponent(cover.filename)}`} alt={render.manifest.brief}/>}<div className="p-4"><p className="text-sm line-clamp-2">{render.manifest.brief}</p><p className="font-mono text-[10px] text-muted mt-2">{render.createdAt.slice(0,10)} · {render.manifest.assets.length} files</p></div></article>;})}</div>}</section>; }

function Panel({ title, body, children }: { title: string; body: string; children: React.ReactNode }) { return <div className="panel p-6"><p className="eyebrow text-bone">{title}</p><p className="text-muted text-sm mt-2 mb-5">{body}</p>{children}</div>; }
function Field({label,value,onChange,disabled}:{label:string;value:string;onChange:(value:string)=>void;disabled:boolean}){return <label className="eyebrow block">{label}<input className="field mt-2 normal-case tracking-normal" value={value} onChange={(e)=>onChange(e.target.value)} disabled={disabled}/></label>;}
function TextArea({label,value,onChange,disabled}:{label:string;value:string;onChange:(value:string)=>void;disabled:boolean}){return <label className="eyebrow block mt-4">{label}<textarea className="field mt-2 min-h-20 normal-case tracking-normal" value={value} onChange={(e)=>onChange(e.target.value)} disabled={disabled}/></label>;}
function NumberField({label,value,min,max,onChange,disabled}:{label:string;value:number;min:number;max:number;onChange:(value:number)=>void;disabled:boolean}){return <label className="eyebrow block mt-3">{label}<input type="number" min={min} max={max} className="field mt-2 normal-case tracking-normal" value={value} onChange={(e)=>onChange(Number(e.target.value))} disabled={disabled}/></label>;}
function SelectField({label,value,values,onChange,disabled}:{label:string;value:string;values:string[];onChange:(value:string)=>void;disabled:boolean}){return <label className="eyebrow block mt-3">{label}<select className="field mt-2 normal-case tracking-normal" value={value} onChange={(e)=>onChange(e.target.value)} disabled={disabled}>{values.map((item)=><option key={item}>{item}</option>)}</select></label>;}
function Toggle({label,checked,onChange,disabled}:{label:string;checked:boolean;onChange:(value:boolean)=>void;disabled:boolean}){return <label className="flex items-center justify-between border border-hairline px-3 py-2 text-sm"><span>{label}</span><input type="checkbox" checked={checked} onChange={(e)=>onChange(e.target.checked)} disabled={disabled}/></label>;}
function AssetStat({value,label}:{value:number;label:string}){return <div className="border border-hairline p-3"><span className="font-display text-2xl font-bold">{value}</span><span className="block font-mono text-[9px] uppercase text-muted">{label}</span></div>;}
function lines(value:string){return [...new Set(value.split(/[\n,]/).map((item)=>item.trim()).filter(Boolean))];}
function assetUrl(ref:string){return ref.startsWith("blob://")?`/api/blob/${ref.slice(7)}`:ref;}
function fileData(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file);});}
function draftFrom(spec:BrandSpec){return {colors:{...spec.identity.colors.roles},displayFamily:spec.identity.typography.display.family,bodyFamily:spec.identity.typography.body.family,spacingUnit:spec.identity.spacing.unit,grid:spec.identity.spacing.grid,clearspace:spec.identity.logo.clearspace,logoMinSize:spec.identity.logo.minSizePx,tone:spec.voice.tone.join(", "),banned:spec.voice.banned.join("\n"),required:spec.voice.required.join("\n"),ctaStyle:spec.voice.ctaStyle,emojiMax:spec.voice.emojiMax,hashtagMax:spec.voice.hashtagMax,alignment:spec.composition.alignment,whitespace:spec.composition.whitespaceMinPct,density:spec.composition.densityMaxElementsPerZone,archetypes:[...spec.composition.layoutArchetypes],photoStyle:spec.imagery.photography.style,photoAllowed:spec.imagery.photography.allowed,illustrationAllowed:spec.imagery.illustration.allowed,aiBackgrounds:spec.imagery.aiFences.backgrounds};}
